Json
utgak/qna pull request #7
Opened 2021-04-10 00:59 UTC by utgak

2021-04-10 14:09 UTC, vkurennov requested changes

2021-04-10 14:09 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    if votes.where(user: user, option: 'up').exists?
вот это лучше вынести в валидацию модели Vote, потому что это ее ответственность валидировать собсдвенные данные

2021-04-10 14:09 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      transaction do
за транзакцию - отдельный плюс, молодец, что ее здесь применил

2021-04-10 14:09 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    if votes.where(user: user, option: 'down').exists?
это тоже в модель Vote, заодно и от дублирования избавишься

2021-04-10 14:09 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    votes.where(option: 'up').count - votes.where(option: 'down').count
а вот тут не лучшее решение, так у тебя 2 запроса к базе происходит и одно вычисление, если голоса хранить как +/- 1, то можно сделать запрос SUM (через одноименный метод у ассоциации) и база сразу вернет сумму, за один запрос. гораздо эффективнее

2021-04-10 14:09 UTC, vkurennov commented on app/models/vote.rb
> +  validates :option, presence: true
лучше value назвать поле

2021-04-10 14:09 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      = link_to '+', vote_up_answer_path(answer), method: :patch, remote: true
примени polymorphic_path и тогда можно ссылки на голосование сделать универсальными и вынести в паршл

2021-04-10 14:09 UTC, vkurennov commented on spec/controllers/concerns/vote_spec.rb
> +RSpec.describe AnswersController, type: :controller do
это не в шаред спеке пишется, а вызывается непсоредсвенно в тестах контроллера, там где все его оставльные тесты

2021-04-10 22:26 UTC, utgak commented on spec/controllers/concerns/vote_spec.rb
> +RSpec.describe AnswersController, type: :controller do
Я так делал появляется ошибка "Could not find shared example"

2021-04-11 10:02 UTC, vkurennov approved these changes

2021-04-11 10:02 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +        if @votable.errors.empty?
лучше через метод `valid?` проверять

2021-04-11 10:02 UTC, vkurennov commented on app/models/vote.rb
> +  def validate_vote_once
вообще-то это можно сделать стандартной валидацией на уникальность (uniqueness)

2021-04-11 10:02 UTC, vkurennov commented on app/views/shared/_voting.html.slim
> +- if !current_user&.author_of?(resource) && user_signed_in?
только условия стоит местами поменять, сначала проверить, что юзер залогинен, а потом что он не автор

2021-04-11 12:07 UTC, merged